<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_63dc062904169',
	'title' => 'HOME V1',
	'fields' => array(
		array(
			'key' => 'field_63dc286f35b3b',
			'label' => 'SESSÃO 1',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_640b772ab4026',
			'label' => 'Categorias 1',
			'name' => 'modulo_02_1',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'taxonomy' => 'cat_doc_1',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'select',
			'allow_null' => 0,
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'multiple' => 0,
		),
		array(
			'key' => 'field_640b784a222c1',
			'label' => 'Categorias 2',
			'name' => 'modulo_02_2',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'taxonomy' => 'cat_doc_1',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'select',
			'allow_null' => 0,
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'multiple' => 0,
		),
		array(
			'key' => 'field_640793f64caa7',
			'label' => 'SESSÃO 2',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_640798175bc59',
			'label' => 'Sessão 2',
			'name' => 'modulo_03_1',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_640798615bc5c',
					'label' => 'Inserir nessa sessão',
					'name' => 'campos_opcionais',
					'aria-label' => '',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'choices' => array(
						'arq_down' => 'Arquivo para Download ( PDF)',
						'cta' => 'CTA',
					),
					'default_value' => array(
					),
					'return_format' => 'value',
					'allow_custom' => 0,
					'layout' => 'horizontal',
					'toggle' => 0,
					'save_custom' => 0,
				),
				array(
					'key' => 'field_6407982f5bc5a',
					'label' => 'Titulo',
					'name' => 'titulo_1',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6407983d5bc5b',
					'label' => 'Descrição',
					'name' => 'titulo_2',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_640799d867ada',
					'label' => 'Imagem da Sessão',
					'name' => 'img',
					'aria-label' => '',
					'type' => 'image_aspect_ratio_crop',
					'instructions' => 'Layout do Figma: </br>
&nbsp;&nbsp;&nbsp;width: 562px </br>
&nbsp;&nbsp;&nbsp;height: 449px </br>
RETINA (preferencialmente)</br>
&nbsp;&nbsp;&nbsp;width: 1124px </br>
&nbsp;&nbsp;&nbsp;height: 898px </br>
TIPO de arquivo - WEBP</br>
Máx tamanho do arquivo - 300kb</br>
Tamanho preferencialmente - 50kb</br>
OBS: para otimizar a imagem, utilize o conversão automática do wordpress na ABA Mídia, ele irá converter a imagem automaticamente em webp',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '60',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'crop_type' => 'aspect_ratio',
					'aspect_ratio_width' => 1124,
					'aspect_ratio_height' => 898,
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => 551,
					'min_height' => 440,
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '.3',
					'mime_types' => 'webp',
				),
				array(
					'key' => 'field_640798b75bc5d',
					'label' => 'Arquivo PDF',
					'name' => 'arquivo_pdf',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_640798615bc5c',
								'operator' => '==',
								'value' => 'arq_down',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'uploader' => '',
					'return_format' => 'array',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
					'library' => 'all',
				),
				array(
					'key' => 'field_640798e15bc5e',
					'label' => 'CTA',
					'name' => 'cta',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_640798615bc5c',
								'operator' => '==',
								'value' => 'cta',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'return_format' => 'array',
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'pagina_home.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'block_editor',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'featured_image',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'pagina' => 'PAGINA',
	),
	'modified' => 1678473471,
));

endif;